name: meatclub
favicon: null
layout_spectrum: 0.24208
typography_spectrum: 0.50417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343339'
    - '#7d6c65'
    - '#5b5a5f'
    - '#acb6b7'
    - '#af9284'
  brandStrength: 0.8933745552785695
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
