name: meatclub
favicon: null
layout_spectrum: 0.9532721342984587
typography_spectrum: 0.024559596087783575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8933745552785695
  lightness: 0.5857679452747107
  saturation: 0.7391488093417138
  rhythmicContrast: 0.3907410765532404
purpose: []
